# 빅 콘테스트 데이터 모델링

In [58]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np
import pickle

In [59]:
# 데이터 불러오기
df_1=pd.read_excel('sell.xlsx') # 판매량
df_2=pd.read_excel('watch.xlsx') # 시청률
test_df = pd.read_excel('test_data.xlsx') # 테스트 데이터

# 데이터 살펴보기

In [60]:
# 데이터 확인
df_1.head(10)

,NS Shop+ 2019.01.01~12.31,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
1,2019-01-01 06:00:00,20,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000
2,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000
3,2019-01-01 06:20:00,20,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000
4,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000
5,2019-01-01 06:40:00,20,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000
6,2019-01-01 06:40:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,9337000
7,2019-01-01 07:00:00,20,100305,200974,오모떼 레이스 파운데이션 브라,속옷,59000,6819000
8,2019-01-01 07:20:00,20,100305,200974,오모떼 레이스 파운데이션 브라,속옷,59000,15689000
9,2019-01-01 07:40:00,20,100305,200974,오모떼 레이스 파운데이션 브라,속옷,59000,25370000

In [61]:
df_2.head(10)

,"NS SHOP+_일자별, 시간대별 시청률 (2019년)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 357,Unnamed: 358,Unnamed: 359,Unnamed: 360,Unnamed: 361,Unnamed: 362,Unnamed: 363,Unnamed: 364,Unnamed: 365,Unnamed: 366
0,시간대,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,...,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31,2019-01-01 to 2019-12-31
1,02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2,02:01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.012,0.003
3,02:02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
4,02:03,0,0,0.014,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
5,02:04,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
6,02:05,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
7,02:06,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
8,02:07,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
9,02:08,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003

In [62]:
test_df.head(10)

,NS Shop+ 2020년 6월 편성,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
1,2020-06-01 06:20:00,20,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN
2,2020-06-01 06:40:00,20,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN
3,2020-06-01 07:00:00,20,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN
4,2020-06-01 07:20:00,20,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN
5,2020-06-01 07:40:00,20,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN
6,2020-06-01 08:00:00,20,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN
7,2020-06-01 08:20:00,20,100381,201247,바비리스 퍼펙트 볼륨스타일러,이미용,59000,NaN
8,2020-06-01 08:40:00,20,100381,201247,바비리스 퍼펙트 볼륨스타일러,이미용,59000,NaN
9,2020-06-01 09:00:00,20,100381,201247,바비리스 퍼펙트 볼륨스타일러,이미용,59000,NaN

In [63]:
df_1.info()
print()
df_2.info()
print()
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38310 entries, 0 to 38309
Data columns (total 8 columns):
NS Shop+ 2019.01.01~12.31    38310 non-null object
Unnamed: 1                   21526 non-null object
Unnamed: 2                   38310 non-null object
Unnamed: 3                   38310 non-null object
Unnamed: 4                   38310 non-null object
Unnamed: 5                   38310 non-null object
Unnamed: 6                   38310 non-null object
Unnamed: 7                   37373 non-null object
dtypes: object(8)
memory usage: 2.3+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1442 entries, 0 to 1441
Columns: 367 entries, NS SHOP+_일자별, 시간대별 시청률 (2019년) to Unnamed: 366
dtypes: object(367)
memory usage: 4.0+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2892 entries, 0 to 2891
Data columns (total 8 columns):
NS Shop+ 2020년 6월 편성    2892 non-null object
Unnamed: 1              1781 non-null object
Unnamed: 2              2892 non-null object
Unnamed: 3              2892 non-null object
Unnamed: 4              2892 non-null object
Unnamed: 5              2892 non-null object
Unnamed: 6              2892 non-null object
Unnamed: 7              1 non-null object
dtypes: object(8)
memory usage: 180.8+ KB

In [65]:
# column 명 변경
new_col_1=df_1.loc[0].tolist()
df_1.columns = new_col_1
df_1.head()

new_col_2=df_2.loc[0].tolist()
df_2.columns = new_col_2
df_2.head()

,시간대,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,...,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31,2019-01-01 to 2019-12-31
0,시간대,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,...,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31,2019-01-01 to 2019-12-31
1,02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2,02:01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.012,0.003
3,02:02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
4,02:03,0,0,0.014,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004

In [66]:
# 중복 column 삭제
df_1=df_1.drop(df_1.index[0])
df_2=df_2.drop(df_2.index[0])
df_2.head(10)

,시간대,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,...,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31,2019-01-01 to 2019-12-31
1,02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2,02:01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.012,0.003
3,02:02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
4,02:03,0,0,0.014,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
5,02:04,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
6,02:05,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.004
7,02:06,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
8,02:07,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
9,02:08,0,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003
10,02:09,0.014,0,0,0,0,0,0,0,0,...,0,0,0.017,0,0,0,0,0,0,0.003

# 데이터 전처리하기

In [67]:
# 결측치 확인, 제거하기
# df_1.info() # 노출(분), 취급액에 NaN 값 존재

# 취급액 column 기준 결측치 들어있는 행 제거
df_1=df_1[df_1['취급액'].notnull()]
# df_1.info()

# 노출(분) column 결측치 대체
df_1=df_1.fillna(method='ffill') # ↑방향 주변값으로 결측치 대체 # ↓방향으로 채우려면 method='bfill'
df_1.info() # column 별 데이터 타입 자동 변경(object → int, float)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37372 entries, 1 to 38304
Data columns (total 8 columns):
방송일시     37372 non-null datetime64[ns]
노출(분)    37372 non-null float64
마더코드     37372 non-null int64
상품코드     37372 non-null int64
상품명      37372 non-null object
상품군      37372 non-null object
판매단가     37372 non-null int64
취급액      37372 non-null int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(2)
memory usage: 2.6+ MB

In [68]:
# 상품명, 상품군 column 처리
df_1['상품군'].value_counts() # 숫자로 대체
df_1['상품군']=df_1['상품군'].replace(['주방', '가전', '의류', '속옷', '잡화', '농수축', '생활용품', '가구', '이미용', '건강기능', '침구'], 
                    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [69]:
df_1.head(10)

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
1,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,2,39900,2099000
2,2019-01-01 06:00:00,20.0,100346,201079,테이트 여성 셀린니트3종,2,39900,4371000
3,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,2,39900,3262000
4,2019-01-01 06:20:00,20.0,100346,201079,테이트 여성 셀린니트3종,2,39900,6955000
5,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,2,39900,6672000
6,2019-01-01 06:40:00,20.0,100346,201079,테이트 여성 셀린니트3종,2,39900,9337000
7,2019-01-01 07:00:00,20.0,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,6819000
8,2019-01-01 07:20:00,20.0,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,15689000
9,2019-01-01 07:40:00,20.0,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,25370000
10,2019-01-01 08:00:00,20.0,100808,202377,CERINI by PAT 남성 소프트 기모 릴렉스팬츠,2,59900,16133000

In [72]:
df_1[df_1['상품군']==3]

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
7,2019-01-01 07:00:00,20.000000,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,6819000
8,2019-01-01 07:20:00,20.000000,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,15689000
9,2019-01-01 07:40:00,20.000000,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,25370000
19,2019-01-01 11:00:00,20.000000,100664,201999,크로커다일 The 편안한 코튼 브라팬티 4세트,3,69900,24531000
20,2019-01-01 11:20:00,20.000000,100664,201999,크로커다일 The 편안한 코튼 브라팬티 4세트,3,69900,49829000
24,2019-01-01 13:00:00,30.000000,100305,200970,오모떼 360도 텐션업 레이스 패키지 시즌4,3,109000,32273000
25,2019-01-01 13:30:00,30.000000,100305,200970,오모떼 360도 텐션업 레이스 패키지 시즌4,3,109000,79273000
42,2019-01-01 19:00:00,20.000000,100607,201892,푸마 에어핏 서포트 브라세트 15종+4종,3,119000,36620000
43,2019-01-01 19:20:00,20.000000,100607,201892,푸마 에어핏 서포트 브라세트 15종+4종,3,119000,69349000
44,2019-01-01 19:40:00,20.000000,100607,201892,푸마 에어핏 서포트 브라세트 15종+4종,3,119000,84610000
56,2019-01-01 23:00:00,20.000000,100718,202108,로베르타 디 까메리노 올레이스 지퍼브라팬티,3,89900,23075000
57,2019-01-01 23:20:00,20.000000,100718,202108,로베르타 디 까메리노 올레이스 지퍼브라팬티,3,89900,39452000
58,2019-01-01 23:40:00,20.000000,100718,202108,로베르타 디 까메리노 올레이스 지퍼브라팬티,3,89900,60010000
65,2019-01-02 01:00:00,20.000000,100193,200652,레이프릴 무빙 맥시풀커버 브라팬티,3,69900,9647000
66,2019-01-02 01:20:00,20.000000,100193,200652,레이프릴 무빙 맥시풀커버 브라팬티,3,69900,15516000
67,2019-01-02 01:40:00,17.100000,100193,200652,레이프릴 무빙 맥시풀커버 브라팬티,3,69900,18695000
74,2019-01-02 08:00:00,20.000000,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,11314000
75,2019-01-02 08:20:00,20.000000,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,21397000
76,2019-01-02 08:40:00,20.000000,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,34822000
109,2019-01-02 14:00:00,30.000000,100305,200970,오모떼 360도 텐션업 레이스 패키지 시즌4,3,109000,28456000
110,2019-01-02 14:30:00,30.000000,100305,200970,오모떼 360도 텐션업 레이스 패키지 시즌4,3,109000,56800000
129,2019-01-02 20:00:00,20.000000,100610,201901,푸마 코튼 라이크라 드로즈 12종,3,89000,18424000
130,2019-01-02 20:00:00,20.000000,100610,201862,푸마 INNO 심리스 롱드로즈 7종,3,89000,422000
131,2019-01-02 20:00:00,20.000000,100610,201880,푸마 드라이셀라인 뉴 런닝 9종,3,89000,1506000
132,2019-01-02 20:20:00,20.000000,100610,201901,푸마 코튼 라이크라 드로즈 12종,3,89000,41096000
133,2019-01-02 20:20:00,20.000000,100610,201862,푸마 INNO 심리스 롱드로즈 7종,3,89000,2575000
134,2019-01-02 20:20:00,20.000000,100610,201880,푸마 드라이셀라인 뉴 런닝 9종,3,89000,3660000
135,2019-01-02 20:40:00,20.000000,100610,201901,푸마 코튼 라이크라 드로즈 12종,3,89000,52885000
136,2019-01-02 20:40:00,20.000000,100610,201862,푸마 INNO 심리스 롱드로즈 7종,3,89000,3029000
137,2019-01-02 20:40:00,20.000000,100610,201880,푸마 드라이셀라인 뉴 런닝 9종,3,89000,4155000
...,...,...,...,...,...,...,...,...
37929,2019-12-27 19:00:00,20.000000,100610,201883,푸마 스트레치 심리스 드로즈 11종,3,89000,51107000
37930,2019-12-27 19:00:00,20.000000,100610,201884,푸마 시그니처 코튼 트렁크 9종,3,89000,5102000
37931,2019-12-27 19:00:00,20.000000,100610,201906,푸마 코튼 언더탑 9종,3,89000,3336000
37986,2019-12-28 12:20:00,20.000000,100195,200655,레이프릴 오가닉 코튼 보정팬티 12종,3,39900,38554000
37987,2019-12-28 12:40:00,20.000000,100195,200655,레이프릴 오가닉 코튼 보정팬티 12종,3,39900,59406000
37988,2019-12-28 13:00:00,20.000000,100195,200655,레이프릴 오가닉 코튼 보정팬티 12종,3,39900,46667000
38097,2019-12-29 20:20:00,20.000000,100610,201883,푸마 스트레치 심리스 드로즈 11종,3,89000,56247000
38098,2019-12-29 20:20:00,20.000000,100610,201884,푸마 시그니처 코튼 트렁크 9종,3,89000,11958000
38099,2019-12-29 20:20:00,20.000000,100610,201906,푸마 코튼 언더탑 9종,3,89000,2156000
38100,2019-12-29 20:40:00,20.000000,100610,201883,푸마 스트레치 심리스 드로즈 11종,3,89000,53682000
38101,2019-12-29 20:40:00,20.000000,100610,201884,푸마 시그니처 코튼 트렁크 9종,3,89000,10565000
38102,2019-12-29 20:40:00,20.000000,100610,201906,푸마 코튼 언더탑 9종,3,89000,4376000
38103,2019-12-29 21:00:00,20.000000,100610,201883,푸마 스트레치 심리스 드로즈 11종,3,89000,81302000
38104,2019-12-29 21:00:00,20.000000,100610,201884,푸마 시그니처 코튼 트렁크 9종,3,89000,12033000
38105,2019-12-29 21:00:00,20.000000,100610,201906,푸마 코튼 언더탑 9종,3,89000,6599000
38138,2019-12-30 06:20:00,20.000000,100302,200967,[완벽더블]오모떼 모달 웜 이너웨어 3세트+3세트,3,49000,10002000
38139,2019-12-30 06:40:00,20.000000,100302,200967,[완벽더블]오모떼 모달 웜 이너웨어 3세트+3세트,3,49000,15177000
38140,2019-12-30 07:00:00,20.000000,100302,200967,[완벽더블]오모떼 모달 웜 이너웨어 3세트+3세트,3,49000,28956000
38193,2019-12-30 23:20:00,20.000000,100610,201883,푸마 스트레치 심리스 드로즈 11종,3,89000,21584000
38194,2019-12-30 23:20:00,20.000000,100610,201884,푸마 시그니처 코튼 트렁크 9종,3,89000,2574000
38195,2019-12-30 23:20:00,20.000000,100610,201906,푸마 코튼 언더탑 9종,3,89000,1436000
38196,2019-12-30 23:40:00,20.000000,100610,201883,푸마 스트레치 심리스 드로즈 11종,3,89000,40882000
38197,2019-12-30 23:40:00,20.000000,100610,201884,푸마 시그니처 코튼 트렁크 9종,3,89000,4417000
38198,2019-12-30 23:40:00,20.000000,100610,201906,푸마 코튼 언더탑 9종,3,89000,2979000
38199,2019-12-31 00:00:00,20.000000,100610,201883,푸마 스트레치 심리스 드로즈 11종,3,89000,45063000
38200,2019-12-31 00:00:00,20.000000,100610,201884,푸마 시그니처 코튼 트렁크 9종,3,89000,4801000
38201,2019-12-31 00:00:00,20.000000,100610,201906,푸마 코튼 언더탑 9종,3,89000,3357000
38208,2019-12-31 01:20:00,20.000000,100439,201357,루시헨느 레이스 홀리데이 란쥬 패키지,3,89900,6540000
38209,2019-12-31 01:40:00,17.166667,100439,201357,루시헨느 레이스 홀리데이 란쥬 패키지,3,89900,22453000
38210,2019-12-31 02:00:00,20.000000,100439,201357,루시헨느 레이스 홀리데이 란쥬 패키지,3,89900,29452000

In [20]:
# # 데이터 중간저장
# with open('dataframe.pkl', 'wb') as f:
#     pickle.dump(df_1, f)
    
# 저장된 데이터 확인하기
with open('dataframe.pkl', 'rb') as f:
    load_df=pickle.load(f) # error 발생
    
load_df.head(10)

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
1,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,2,39900,2099000
2,2019-01-01 06:00:00,20.0,100346,201079,테이트 여성 셀린니트3종,2,39900,4371000
3,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,2,39900,3262000
4,2019-01-01 06:20:00,20.0,100346,201079,테이트 여성 셀린니트3종,2,39900,6955000
5,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,2,39900,6672000
6,2019-01-01 06:40:00,20.0,100346,201079,테이트 여성 셀린니트3종,2,39900,9337000
7,2019-01-01 07:00:00,20.0,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,6819000
8,2019-01-01 07:20:00,20.0,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,15689000
9,2019-01-01 07:40:00,20.0,100305,200974,오모떼 레이스 파운데이션 브라,3,59000,25370000
10,2019-01-01 08:00:00,20.0,100808,202377,CERINI by PAT 남성 소프트 기모 릴렉스팬츠,2,59900,16133000

In [21]:
# 상품명 성별 포함 고려해 새로운 column 추가하기
condition_li=[
    (load_df['상품명'].str.contains('남성')),
    (load_df['상품명'].str.contains('여성')),
    (load_df['상품명'].str.contains('브라')),
    (load_df['상품명'].str.contains('오모떼')),
    (load_df['상품명'].str.contains('보정팬티')),
    (load_df['상품명'].str.contains('뷰티'))
]
value_li=[1, 2, 2, 2, 2, 2]
load_df['성별 포함']=np.select(condition_li,value_li)

In [22]:
# 방송일시 전처리하기
load_df['년']=load_df['방송일시'].dt.year
load_df['월']=load_df['방송일시'].dt.month
load_df['일자']=load_df['방송일시'].dt.day
load_df['시']=load_df['방송일시'].dt.hour
load_df['분']=load_df['방송일시'].dt.minute
load_df['초']=load_df['방송일시'].dt.second

In [52]:
# 데이터 중간저장
with open('dataframe_2.pkl', 'wb') as f:
    pickle.dump(load_df, f)

print('데이터 저장이 완료되었습니다.')

데이터 저장이 완료되었습니다.

# train/test 데이터 분리

In [73]:
# 라이브러리 불러오기
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import warnings
from sklearn.utils.testing import all_estimators
warnings.filterwarnings('ignore')

In [86]:
# train 데이터
x = load_df[['노출(분)', '마더코드', '상품코드', '상품군', '판매단가', '성별 포함', '월', '일자', '시', '분']]
# 정답 데이터
y = load_df['취급액']

x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37372 entries, 1 to 38304
Data columns (total 10 columns):
노출(분)    37372 non-null float64
마더코드     37372 non-null int64
상품코드     37372 non-null int64
상품군      37372 non-null int64
판매단가     37372 non-null int64
성별 포함    37372 non-null int32
월        37372 non-null int64
일자       37372 non-null int64
시        37372 non-null int64
분        37372 non-null int64
dtypes: float64(1), int32(1), int64(8)
memory usage: 3.0 MB

In [87]:
x.head(10)

    노출(분)    마더코드    상품코드  상품군   판매단가  성별 포함  월  일자  시   분
1    20.0  100346  201072    2  39900      1  1   1  6   0
2    20.0  100346  201079    2  39900      2  1   1  6   0
3    20.0  100346  201072    2  39900      1  1   1  6  20
4    20.0  100346  201079    2  39900      2  1   1  6  20
5    20.0  100346  201072    2  39900      1  1   1  6  40
6    20.0  100346  201079    2  39900      2  1   1  6  40
7    20.0  100305  200974    3  59000      2  1   1  7   0
8    20.0  100305  200974    3  59000      2  1   1  7  20
9    20.0  100305  200974    3  59000      2  1   1  7  40
10   20.0  100808  202377    2  59900      1  1   1  8   0

In [88]:
y.head(10)

1      2099000
2      4371000
3      3262000
4      6955000
5      6672000
6      9337000
7      6819000
8     15689000
9     25370000
10    16133000
Name: 취급액, dtype: int64

In [89]:
# 데이터 split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, train_size=0.7)

# model_selection으로 모델링/정확도 비교

In [90]:
# 'regressor'에 속하는 모델 확인하기

allAlgorithms=all_estimators(type_filter='regressor')
print('regressor 모델 리스트 : {}'.format(allAlgorithms), sep='\n')
print('시험할 수 있는 regressor 모델 개수: {}'.format(len(allAlgorithms)))

regressor 모델 리스트 : [('ARDRegression', <class 'sklearn.linear_model.bayes.ARDRegression'>), ('AdaBoostRegressor', <class 'sklearn.ensemble.weight_boosting.AdaBoostRegressor'>), ('BaggingRegressor', <class 'sklearn.ensemble.bagging.BaggingRegressor'>), ('BayesianRidge', <class 'sklearn.linear_model.bayes.BayesianRidge'>), ('CCA', <class 'sklearn.cross_decomposition.cca_.CCA'>), ('DecisionTreeRegressor', <class 'sklearn.tree.tree.DecisionTreeRegressor'>), ('ElasticNet', <class 'sklearn.linear_model.coordinate_descent.ElasticNet'>), ('ElasticNetCV', <class 'sklearn.linear_model.coordinate_descent.ElasticNetCV'>), ('ExtraTreeRegressor', <class 'sklearn.tree.tree.ExtraTreeRegressor'>), ('ExtraTreesRegressor', <class 'sklearn.ensemble.forest.ExtraTreesRegressor'>), ('GaussianProcessRegressor', <class 'sklearn.gaussian_process.gpr.GaussianProcessRegressor'>), ('GradientBoostingRegressor', <class 'sklearn.ensemble.gradient_boosting.GradientBoostingRegressor'>), ('HuberRegressor', <class 'sklearn.linear_model.huber.HuberRegressor'>), ('KNeighborsRegressor', <class 'sklearn.neighbors.regression.KNeighborsRegressor'>), ('KernelRidge', <class 'sklearn.kernel_ridge.KernelRidge'>), ('Lars', <class 'sklearn.linear_model.least_angle.Lars'>), ('LarsCV', <class 'sklearn.linear_model.least_angle.LarsCV'>), ('Lasso', <class 'sklearn.linear_model.coordinate_descent.Lasso'>), ('LassoCV', <class 'sklearn.linear_model.coordinate_descent.LassoCV'>), ('LassoLars', <class 'sklearn.linear_model.least_angle.LassoLars'>), ('LassoLarsCV', <class 'sklearn.linear_model.least_angle.LassoLarsCV'>), ('LassoLarsIC', <class 'sklearn.linear_model.least_angle.LassoLarsIC'>), ('LinearRegression', <class 'sklearn.linear_model.base.LinearRegression'>), ('LinearSVR', <class 'sklearn.svm.classes.LinearSVR'>), ('MLPRegressor', <class 'sklearn.neural_network.multilayer_perceptron.MLPRegressor'>), ('MultiTaskElasticNet', <class 'sklearn.linear_model.coordinate_descent.MultiTaskElasticNet'>), ('MultiTaskElasticNetCV', <class 'sklearn.linear_model.coordinate_descent.MultiTaskElasticNetCV'>), ('MultiTaskLasso', <class 'sklearn.linear_model.coordinate_descent.MultiTaskLasso'>), ('MultiTaskLassoCV', <class 'sklearn.linear_model.coordinate_descent.MultiTaskLassoCV'>), ('NuSVR', <class 'sklearn.svm.classes.NuSVR'>), ('OrthogonalMatchingPursuit', <class 'sklearn.linear_model.omp.OrthogonalMatchingPursuit'>), ('OrthogonalMatchingPursuitCV', <class 'sklearn.linear_model.omp.OrthogonalMatchingPursuitCV'>), ('PLSCanonical', <class 'sklearn.cross_decomposition.pls_.PLSCanonical'>), ('PLSRegression', <class 'sklearn.cross_decomposition.pls_.PLSRegression'>), ('PassiveAggressiveRegressor', <class 'sklearn.linear_model.passive_aggressive.PassiveAggressiveRegressor'>), ('RANSACRegressor', <class 'sklearn.linear_model.ransac.RANSACRegressor'>), ('RadiusNeighborsRegressor', <class 'sklearn.neighbors.regression.RadiusNeighborsRegressor'>), ('RandomForestRegressor', <class 'sklearn.ensemble.forest.RandomForestRegressor'>), ('Ridge', <class 'sklearn.linear_model.ridge.Ridge'>), ('RidgeCV', <class 'sklearn.linear_model.ridge.RidgeCV'>), ('SGDRegressor', <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'>), ('SVR', <class 'sklearn.svm.classes.SVR'>), ('TheilSenRegressor', <class 'sklearn.linear_model.theil_sen.TheilSenRegressor'>), ('TransformedTargetRegressor', <class 'sklearn.compose._target.TransformedTargetRegressor'>)]
시험할 수 있는 regressor 모델 개수: 44

In [91]:
# 머신러닝 모델 불러오기
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor, ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor, XGBRFRegressor

# 모델 적용
model_RF=RandomForestRegressor(random_state=66)
model_ADB=AdaBoostRegressor(random_state=66)
model_GB=GradientBoostingRegressor(random_state=66)
model_DT=DecisionTreeRegressor(random_state=66)
model_XGB=XGBRegressor(random_state=66)
model_XGBRF=XGBRFRegressor(random_state=66)

model_RF.fit(x_train, y_train)
model_ADB.fit(x_train, y_train)
model_GB.fit(x_train, y_train)
model_DT.fit(x_train, y_train)
model_XGB.fit(x_train, y_train)
model_XGBRF.fit(x_train, y_train)

# 정확도
print("RF 훈련 정확도 : {:.3f}".format(model_RF.score(x_train, y_train)))
print("RF 테스트 정확도 : {:.3f}".format(model_RF.score(x_test, y_test)))

print("ADB 훈련 정확도 : {:.3f}".format(model_ADB.score(x_train, y_train)))
print("ADB 테스트 정확도 : {:.3f}".format(model_ADB.score(x_test, y_test)))

print("GB 훈련 정확도 : {:.3f}".format(model_GB.score(x_train, y_train)))
print("GB 테스트 정확도 : {:.3f}".format(model_GB.score(x_test, y_test)))

print("DT 훈련 정확도 : {:.3f}".format(model_DT.score(x_train, y_train)))
print("DT 테스트 정확도 : {:.3f}".format(model_DT.score(x_test, y_test)))

print("XGB 훈련 정확도 : {:.3f}".format(model_DT.score(x_train, y_train)))
print("XGB 테스트 정확도 : {:.3f}".format(model_DT.score(x_test, y_test)))

print("XGBRF 훈련 정확도 : {:.3f}".format(model_DT.score(x_train, y_train)))
print("XGBRF 테스트 정확도 : {:.3f}".format(model_DT.score(x_test, y_test)))

RF 훈련 정확도 : 0.939
RF 테스트 정확도 : 0.653
ADB 훈련 정확도 : 0.076
ADB 테스트 정확도 : 0.040
GB 훈련 정확도 : 0.504
GB 테스트 정확도 : 0.483
DT 훈련 정확도 : 1.000
DT 테스트 정확도 : 0.457
XGB 훈련 정확도 : 1.000
XGB 테스트 정확도 : 0.457
XGBRF 훈련 정확도 : 1.000
XGBRF 테스트 정확도 : 0.457

In [44]:
# 모델 적용
model_RF=RandomForestRegressor(random_state=66)
model_GB=GradientBoostingRegressor(random_state=66)
model_DT=DecisionTreeRegressor(random_state=66)

model_RF.fit(x_train, y_train)
model_GB.fit(x_train, y_train)
model_DT.fit(x_train, y_train)

# 정확도
print("RF 훈련 정확도 : {:.3f}".format(model_RF.score(x_train, y_train)))
print("RF 테스트 정확도 : {:.3f}".format(model_RF.score(x_test, y_test)))

print("GB 훈련 정확도 : {:.3f}".format(model_GB.score(x_train, y_train)))
print("GB 테스트 정확도 : {:.3f}".format(model_GB.score(x_test, y_test)))

print("DT 훈련 정확도 : {:.3f}".format(model_DT.score(x_train, y_train)))
print("DT 테스트 정확도 : {:.3f}".format(model_DT.score(x_test, y_test)))

RF 훈련 정확도 : 0.942
RF 테스트 정확도 : 0.653
GB 훈련 정확도 : 0.506
GB 테스트 정확도 : 0.502
DT 훈련 정확도 : 1.000
DT 테스트 정확도 : 0.429

# 시청률 자료 추가하기

In [54]:
# 일별 시청률 평균 column 추가
df_2.T # 행/열 반전

,1,2,3,4,5,6,7,8,9,10,...,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441
시간대,02:00,02:01,02:02,02:03,02:04,02:05,02:06,02:07,02:08,02:09,...,01:51,01:52,01:53,01:54,01:55,01:56,01:57,01:58,01:59,월화수목금토일02:00-01:59
2019-01-01,0,0,0,0,0,0,0,0,0,0.014,...,0,0,0,0,0,0,0,0,0,0.004
2019-01-02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.006
2019-01-03,0,0,0,0.014,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.002
2019-01-04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-01-05,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.027,0,0,0,0.002
2019-01-06,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-01-07,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-01-08,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.002
2019-01-09,0,0,0,0,0,0,0,0,0,0,...,0.004,0.004,0.004,0.004,0.004,0,0.004,0.004,0.004,0.003
2019-01-10,0,0.005,0.005,0.005,0.005,0.005,0.005,0.005,0,0,...,0,0,0,0,0,0,0,0,0,0.002
2019-01-11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0.009,0.009,0.014,0.001
2019-01-12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.002
2019-01-13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.002
2019-01-14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0.033,0.086,0,0.004
2019-01-15,0,0,0,0,0,0.015,0.015,0.015,0,0,...,0,0,0,0,0,0,0,0,0,0.002
2019-01-16,0,0,0,0,0,0,0,0,0,0,...,0.005,0.005,0.005,0.005,0.005,0.005,0.005,0.005,0.005,0.002
2019-01-17,0.006,0.006,0.006,0.006,0.006,0.006,0.006,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
2019-01-18,0,0,0,0,0,0,0,0,0,0,...,0.026,0.026,0,0,0,0,0,0,0,0.002
2019-01-19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-01-20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.001
2019-01-21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-01-22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0.015,0,0,0.002
2019-01-23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.002
2019-01-24,0,0,0,0,0,0.005,0.005,0,0,0,...,0,0,0,0,0,0,0,0,0,0.002
2019-01-25,0,0,0,0,0,0,0.034,0.034,0,0.006,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.043,0.004,0.003
2019-01-26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-01-27,0,0,0,0,0,0,0,0,0,0,...,0.008,0,0,0,0,0,0,0,0,0.001
2019-01-28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-01-29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-03,0.048,0.048,0.033,0.033,0.033,0.033,0.033,0.033,0.033,0.033,...,0,0,0,0,0,0,0,0,0,0.005
2019-12-04,0,0,0,0,0,0,0,0,0,0,...,0.012,0,0,0,0,0,0,0,0,0.005
2019-12-05,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-12-06,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.006
2019-12-07,0,0,0,0,0,0,0.024,0.024,0.024,0.024,...,0.019,0.019,0.019,0.019,0.058,0.07,0.07,0.07,0.07,0.007
2019-12-08,0.018,0.018,0.018,0.018,0.018,0.018,0.018,0.018,0.018,0.018,...,0.017,0,0,0,0,0,0,0,0,0.007
2019-12-09,0,0,0.018,0.018,0,0,0,0,0,0,...,0.036,0.036,0.036,0.036,0.036,0.036,0.036,0.036,0.036,0.007
2019-12-10,0.035,0.035,0.035,0.035,0.035,0.035,0.035,0.035,0.035,0.035,...,0.031,0.031,0.031,0.031,0.031,0.031,0.031,0.031,0.031,0.007
2019-12-11,0.03,0.03,0.067,0.067,0.067,0.03,0.03,0.03,0.03,0.03,...,0,0,0,0,0,0,0,0,0,0.007
2019-12-12,0.016,0.016,0.016,0.016,0.016,0.016,0.016,0.016,0.016,0.016,...,0,0,0,0,0,0,0,0.024,0,0.005
2019-12-13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-12-14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.015,0.005
2019-12-15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-12-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
2019-12-17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.009,0.009,0.009,0.009,0,0.004
2019-12-18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
2019-12-19,0,0,0,0,0,0,0,0,0,0.016,...,0,0,0,0,0,0,0,0,0,0.004
2019-12-20,0.012,0.012,0.012,0.012,0.012,0.012,0.012,0,0,0,...,0.036,0.036,0.036,0.036,0.036,0.013,0,0,0,0.014
2019-12-21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.003
2019-12-22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
2019-12-23,0,0,0,0,0,0,0,0,0,0,...,0.013,0.013,0.013,0.013,0.013,0.013,0.013,0.013,0.013,0.01
2019-12-24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.017,0,0.006
2019-12-25,0,0,0,0.017,0.017,0.017,0.017,0.017,0.017,0.017,...,0,0,0,0,0,0,0,0,0,0.006
2019-12-26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.007
2019-12-27,0,0,0,0,0,0,0,0,0,0,...,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.004
2019-12-28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.006
2019-12-29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.004
2019-12-30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.019,0,0.005
2019-12-31,0,0.012,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.005
2019-01-01 to 2019-12-31,0.003,0.003,0.004,0.004,0.004,0.004,0.003,0.003,0.003,0.003,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004